---
- name: Модифицируйте плейбук
  hosts: all
  become: true
  vars:
    custom_motd: |
      ====================================================
      Welcome to managed server!
      Hostname: {{ ansible_facts['hostname'] }}
      IP Address: {{ ansible_facts['default_ipv4']['address'] }}
      
      Have a great day, System Administrator!
      ====================================================
  tasks:
    - name: Изменение приветствия системы (motd)
      ansible.builtin.copy:
        content: "{{ custom_motd }}"
        dest: /etc/motd
        mode: '0644'